version: '3.1'

services:
  db:
    container_name: pg_container
    hostname: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres
  pgadmin:
    depends_on:
      - db
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

    ports:
      - "5050:80"
    volumes:
    - dbdata:/var/lib/pgadmin
volumes:
  dbdata:
    driver: azure_file
    driver_opts:
      share_name: acishare
      storage_account_name: mystorageaccount1412


